---
title: "FINAL PROJECT"
author: 'Michelle Pogue & Gerardo Hernandez'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 'Introduction'


```{r}
Billionaire_data <- read.csv('/Users/17135/OneDrive/DATA 2401/Billionaire.csv', stringsAsFactors = F)
tuition_data <- read.csv('/Users/17135/OneDrive/DATA 2401/degrees-that-pay-back.csv', stringsAsFactors = F)
```

## 'Packages Required'


```{r}
install.packages('dplyr')
library(dplyr)

```

## 'Data Required'


```{r}
read.csv('../DATA 2401/Billionaire.csv', stringsAsFactors = F)
read.csv('../DATA 2401/degrees-that-pay-back.csv',stringsAsFactors = F)
```

## 'Data Preperation'


```{r}
Billionaire_data <- read.csv('../DATA 2401/Billionaire.csv', stringsAsFactors = F)
glimpse(Billionaire_data)
tuition_data <- read.csv('../DATA 2401/degrees-that-pay-back.csv',stringsAsFactors = F)
glimpse(tuition_data)

```

## 'Exploratory Data Analysis'


```{r}
#We want to know ones who make the most money, lets filter out the top 8 billionaires. 
top_money<- billionaire_data %>%
  arrange(Rank) %>%
  head(8)

top_money 

```

## 'Summary'


```{r}


```


